MOVE_MODE_WALK = "WALK"
MOVE_MODE_JUMP = "JUMP"

POINT_TYPE_PASS = "PASS"
POINT_TYPE_TARGET = "TARGET"

ACTION_TELEPORT = "TELEPORT"
ACTION_PICK_UP = "PICK_UP"
ACTION_CATCH_INSECT = "CATCH_INSECT"
ACTION_CLEAN_ANIMAL = "CLEAN_ANIMAL"
ACTION_WAIT = "WAIT"